# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xci
# IP: The module: 'system_LEDs_4Bits_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xci
# IP: The module: 'system_LEDs_4Bits_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_LEDs_4Bits_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
