# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_2/system_xbar_2.xci
# IP: The module: 'system_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_2/system_xbar_2.xci
# IP: The module: 'system_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
