# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/constraints/base.xdc

# Block Designs: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_BTNs_4Bits_0/system_BTNs_4Bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_BTNs_4Bits_0 || ORIG_REF_NAME==system_BTNs_4Bits_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LEDs_4Bits_1 || ORIG_REF_NAME==system_LEDs_4Bits_1}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_SWs_4Bits_2/system_SWs_4Bits_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_SWs_4Bits_2 || ORIG_REF_NAME==system_SWs_4Bits_2}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_dispctrl_0_0/system_axi_dispctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dispctrl_0_0 || ORIG_REF_NAME==system_axi_dispctrl_0_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_dispctrl_1_1/system_axi_dispctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dispctrl_1_1 || ORIG_REF_NAME==system_axi_dispctrl_1_1}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_i2s_adi_1_0/system_axi_i2s_adi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_i2s_adi_1_0 || ORIG_REF_NAME==system_axi_i2s_adi_1_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_ground_0/system_ground_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ground_0 || ORIG_REF_NAME==system_ground_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_hdmi_tx_0_0/system_hdmi_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_tx_0_0 || ORIG_REF_NAME==system_hdmi_tx_0_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_vdd_1/system_vdd_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdd_1 || ORIG_REF_NAME==system_vdd_1}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_ps7_0_axi_periph_3/system_ps7_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_3 || ORIG_REF_NAME==system_ps7_0_axi_periph_3}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_rst_ps7_0_100M_3/system_rst_ps7_0_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_3 || ORIG_REF_NAME==system_rst_ps7_0_100M_3}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_axi_mem_intercon_4/system_axi_mem_intercon_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_4 || ORIG_REF_NAME==system_axi_mem_intercon_4}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_rst_ps7_0_150M_3/system_rst_ps7_0_150M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_150M_3 || ORIG_REF_NAME==system_rst_ps7_0_150M_3}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2}]

# XDC: /mnt/workspace/znsoc/Projects/zybo_bsd/sources/hardware/src/bd/system/system_ooc.xdc
